"""add refresh_token table

Revision ID: d37d57c953ff
Revises: 0be51fd8e0f5
Create Date: 2026-07-30 23:03:49.205007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37d57c953ff'
down_revision: Union[str, Sequence[str], None] = '0be51fd8e0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


role_table = sa.table(
    "role",
    sa.column("id", sa.SmallInteger),
    sa.column("code", sa.String),
    sa.column("name", sa.String),
    schema="core",
)

seed_roles = [
    {"id": 1, "code": "ADMIN", "name": "Administrador"},
    {"id": 2, "code": "TEACHER", "name": "Docente"},
    {"id": 3, "code": "STUDENT", "name": "Estudiante"},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    schema='core'
    )
    # ### end Alembic commands ###

    op.bulk_insert(role_table, seed_roles)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM core.role WHERE code IN ('ADMIN', 'TEACHER', 'STUDENT')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token', schema='core')
    # ### end Alembic commands ###
